# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy to production

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  deploy-production:
    if: github.ref == 'refs/heads/main'
    runs-on: self-hosted
    concurrency: deploy-to-production
    environment: production
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
      - name: Install yarn
        run: npm install -g yarn
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build image
        run: yarn build
      - name: Remove node_modules
        run: rm -rf node_module
      - name: Install production dependencies
        run: yarn --production
      - name: Clean up
        if: always()
        run: npm uninstall -g yarn
      - name: Create .env file"
        uses: SpicyPizza/create-envfile@v2.0
        with:
          file_name: .env
          envkey_NODE_ENV: "PRODUCTION"
          envkey_DATABASE_URL: "${{ secrets.DATABASE_URL }}"
          envkey_RABBITMQ_URL: "${{ secrets.RABBITMQ_URL }}"
          envkey_RABBITMQ_USERS_QUEUE: "${{ secrets.RABBITMQ_USERS_QUEUE }}"
          envkey_REDIS_PORT: "${{ secrets.REDIS_PORT }}"
          envkey_REDIS_HOST: "${{ secrets.REDIS_HOST }}"
          envkey_REDIS_PASSWORD: "${{ secrets.REDIS_PASSWORD }}"
          envkey_REDIS_TTL: "${{ secrets.REDIS_TTL }}"
          envkey_LOG_NIVEL: "${{ secrets.LOG_NIVEL }}"
          envkey_APP_PORT: "${{ secrets.APP_PORT }}"
          envkey_CARDS_SERVICE_URL: "${{ secrets.CARDS_SERVICE_URL }}"
          envkey_USERS_SERVICE_URL: "${{ secrets.USERS_SERVICE_URL }}"
          envkey_USERS_TOKEN_SECRET: "${{ secrets.USERS_TOKEN_SECRET }}"
          envkey_NEW_RELIC_APP_NAME: "${{ secrets.NEW_RELIC_APP_NAME }}"
          envkey_NEW_RELIC_LABELS: "${{ secrets.NEW_RELIC_LABELS }}"
          envkey_NEW_RELIC_LICENSE_KEY: "${{ secrets.NEW_RELIC_LICENSE_KEY }}"
          envkey_NEW_RELIC_LOG: "${{ secrets.NEW_RELIC_LOG }}"
          envkey_NEW_RELIC_LOG_LEVEL: "${{ secrets.NEW_RELIC_LOG_LEVEL }}"
          envkey_NEW_RELIC_NO_CONFIG_FILE: "${{ secrets.NEW_RELIC_NO_CONFIG_FILE }}"
      - name: Update server
        run: pm2 restart server